id: PA73A0F75
initial_creation_type: input
source_metadata:
  title: Pakchok Dorje Series
  language: en
  description: 'Texts by and about Sé Pakchok Dorje (sras ''phags mchog rdo rje, 1893–1943),
    a mind emanation of Jamyang Khyentse Wangpo (1820–1892) and one of the six sons
    of Tokden Śākya Śrī (1853–1919):'
  volume:
    1010e55c91254217a75e684a976f77c1:
      title: Prayer to Sé Pakchok Dorje
      parent: Prayers
created_at: '2022-03-01T01:09:28.986209'
last_modified_at: '2022-03-01T01:09:28.986215'
